import React from "react";
import styles from "../styles/Home.module.css";
import Head from "next/head";
import {NavigationBar} from "./NavigationBar";

const HEADER_LOGO = '/main-logo-2.png'
const FOOTER_LOGO = '/main-logo.png'


const Layout = ({children}: any) => {

    return (
        <>
            <NavigationBar/>
            <div className={styles.container}>
                <Head>
                    <title>Uch∞se</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href={HEADER_LOGO}/>
                </Head>
                <main className={styles.main}>
                    {children}
                </main>
                <footer>
                    <a
                        href="#"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        Made by{' '}
                        <span className={styles.logo}>
                        <img src={FOOTER_LOGO} alt="LifeLoopTeam" style={{width: '120px', marginTop: '-15px'}}/>
                    </span>
                    </a>
                </footer>
            </div>
        </>
    );
}

export default Layout;
