import React from "react";
import styles from "../styles/Home.module.css";
import Head from "next/head";
import {NavigationBar} from "./NavigationBar";
import {Footer} from "./Footer";
import {HEADER_LOGO} from "../constants/constants";


const Layout = ({children}: any) => {

    return (
        <>
            <NavigationBar/>
            <div className={styles.container}>
                <Head>
                    <title>Uch∞se</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href={HEADER_LOGO}/>
                </Head>
                <main className={styles.main}>
                    {children}
                </main>
            <Footer/>
            </div>
        </>
    );
}

export default Layout;
